apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # name of the ClusterRole
  name: metrics-server-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
